version: "3"

services:
  # API
  app:
    container_name: api-casamento
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
    depends_on: 
      - mongodb

  # DATABASE
  mongodb:
    image: mongo
    container_name: api-mongodb
    volumes:
      - ./dockervolume:/data/db
    ports:
      - 27017:27017