version: "3"
services:
  # API
  api_casamento:
    container_name: API_CASAMENTO
    build: .
    command: yarn dev
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - MONGODB_URI=mongodb://mongodb/api_casamento
    links: 
      - mongodb

  # DATABASE
  mongodb:
    image: mongo
    container_name: "MONGO"
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017