version: "3"

services:
  # API
  casamento:
    container_name: api_casamento
    build: .
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
    depends_on: 
      - mongodb
    command: yarn dev

  # DATABASE
  mongodb:
    image: mongo
    container_name: api_mongodb
    ports:
      - 27017:27017